# Generated by Django 4.0.4 on 2022-04-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_alter_car_options_car_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_file',
            field=models.FileField(upload_to=''),
        ),
    ]
