# Generated by Django 4.0.4 on 2022-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_alter_car_description_alter_car_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
