# Generated by Django 4.0.4 on 2022-04-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_alter_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image_file',
            new_name='image',
        ),
    ]
